package com.example.waterquality.ui.utils

import androidx.compose.runtime.compositionLocalOf

/** Composition-local that carries the current app language ("English" or "ಕನ್ನಡ"). */
val LocalAppLanguage = compositionLocalOf { "English" }

/** Returns the localized string for [key] based on the current [language]. */
fun appStr(language: String, key: String): String =
    (if (language == "ಕನ್ನಡ") KN else EN)[key] ?: key

// ── English ───────────────────────────────────────────────────────────────────
private val EN = mapOf(
    // Bottom nav
    "nav_home"          to "Home",
    "nav_map"           to "Map",
    "nav_advisories"    to "Advisories",
    "nav_alerts"        to "Alerts",
    "nav_profile"       to "Profile",
    // Greetings
    "greet_morning"     to "Good Morning",
    "greet_afternoon"   to "Good Afternoon",
    "greet_evening"     to "Good Evening",
    "greet_night"       to "Good Night",
    // Home
    "home_subtitle"     to "Water Quality Monitor",
    "home_wqi"          to "Water Quality Index",
    "home_region"       to "Bengaluru Region",
    "home_reports"      to "Reports",
    "home_clean"        to "Clean",
    "home_alerts"       to "Alerts",
    "home_actions"      to "Quick Actions",
    "home_new_report"   to "New Report",
    "home_view_map"     to "View Map",
    "home_advisories"   to "Advisories",
    "home_recent"       to "Recent Reports",
    "home_empty"        to "No reports yet",
    "home_empty_sub"    to "Submit your first water quality report",
    "home_see_all"      to "See all",
    "home_tap_report"   to "Tap a card for details",
    "home_offline"      to "You're offline — showing cached data",
    "home_trend"        to "7-Day WQI Trend",
    "home_today"        to "Today",
    "home_7d_ago"       to "7d ago",
    "home_live"         to "LIVE",
    "home_report_brkdn" to "Report Breakdown",
    "home_total_rep"    to "Total Reports",
    "home_tap_map"      to "Tap to open full map",
    "home_gemini_title" to "Gemini AI Insights",
    "home_gemini_insight" to "Water quality in %s is mostly clean. %s of sources are safe.",
    "home_member"       to "Member for",
    "home_days"         to "days",
    // Map
    "map_title"         to "Water Map",
    "map_all"           to "All",
    "map_clean"         to "Clean",
    "map_moderate"      to "Moderate",
    "map_polluted"      to "Polluted",
    "map_empty"         to "No reports here",
    "map_empty_sub"     to "Submit a report to pin it on the map",
    "map_detail"        to "Water Source Detail",
    // Report submission
    "rep_title"         to "Submit Report",
    "rep_cancel"        to "Cancel",
    "rep_photo"         to "Capture Water Photo",
    "rep_photo_hint"    to "Take a clear photo of the water source",
    "rep_tap_cam"       to "Tap to open camera",
    "rep_retake"        to "Retake Photo",
    "rep_details"       to "Water Details",
    "rep_clarity"       to "Water Clarity",
    "rep_murky"         to "Murky",
    "rep_crystal"       to "Crystal Clear",
    "rep_smell"         to "Smell",
    "rep_normal"        to "Normal",
    "rep_bad"           to "Bad",
    "rep_flow"          to "Flow Rate",
    "rep_low"           to "Low",
    "rep_medium"        to "Medium",
    "rep_high"          to "High",
    "rep_location"      to "GPS Location",
    "rep_loc_hint"      to "We need your location to pin the report on the map.",
    "rep_loc_cap"       to "Location captured ✓",
    "rep_loc_none"      to "Location not captured",
    "rep_loc_sub"       to "Tap below to get your GPS coordinates",
    "rep_get_loc"       to "Get My Location",
    "rep_refresh_loc"   to "Refresh Location",
    "rep_continue"      to "Continue",
    "rep_submit"        to "Submit Report",
    "rep_back"          to "Back",
    "rep_submitted"     to "Report Submitted!",
    "rep_thanks"        to "Thank you for contributing",
    // Alerts
    "al_title"          to "Alert Feed",
    "al_hint"           to "Swipe left to dismiss an alert",
    "al_empty"          to "All clear!",
    "al_empty_sub"      to "No active alerts in your area",
    "al_dismiss"        to "Dismiss",
    "al_all"            to "All",
    // Advisories
    "adv_title"         to "AI Advisories",
    "adv_subtitle"      to "Swipe to explore water quality insights",
    "adv_empty"         to "No advisories yet",
    "adv_empty_sub"     to "Submit reports to generate AI-powered advisories",
    // Profile
    "pro_title"         to "Profile",
    "pro_reports"       to "Reports",
    "pro_streak"        to "Streak",
    "pro_badges"        to "Badges",
    "pro_preferences"   to "Preferences",
    "pro_dark"          to "Dark Mode",
    "pro_light"         to "Light Mode",
    "pro_notif"         to "Push Notifications",
    "pro_language"      to "Language",
    "pro_about"         to "About",
    "pro_version"       to "App Version",
    "pro_data"          to "Data Source",
    "pro_ai"            to "AI Engine",
    "pro_member_for"    to "Member for",
    "pro_days"          to "days",
    // Report details
    "det_title"         to "Report Details",
    "det_analysis"      to "Water Analysis",
    "det_ai_advisory"   to "AI Advisory",
    // Common
    "status_clean"      to "Clean",
    "status_moderate"   to "Moderate",
    "status_polluted"   to "Polluted",
    "close"             to "Close",
    "ai_advisory"       to "AI Advisory",
    "clarity"           to "Clarity",
    "smell"             to "Smell",
    "flow"              to "Flow",
    "location"          to "Location",
    "reported"          to "Reported",
    "status"            to "Status",
    "share_report"      to "Share Water Report",
    "murky"             to "Murky",
    "crystal_clear"     to "Crystal Clear",
    // AI Insights
    "ai_clean_insight"  to "✅ Water quality in {region} is in good condition. {clean} of {total} reports show clean water. Continue routine monitoring.",
    "ai_mod_insight"    to "⚠️ Water quality shows moderate conditions. Some sources may need treatment before use. Regular testing and boiling water is advised.",
    "ai_poll_insight"   to "🚨 {polluted} of {total} reports indicate contaminated water. Avoid contact. Alert local authorities immediately.",
    "ai_updated"        to "Based on {total} community reports",
)

// ── ಕನ್ನಡ ────────────────────────────────────────────────────────────────────
private val KN = mapOf(
    "nav_home"          to "ಮನೆ",
    "nav_map"           to "ನಕ್ಷೆ",
    "nav_advisories"    to "ಸಲಹೆಗಳು",
    "nav_alerts"        to "ಎಚ್ಚರಿಕೆಗಳು",
    "nav_profile"       to "ಪ್ರೊಫೈಲ್",
    "greet_morning"     to "ಶುಭೋದಯ",
    "greet_afternoon"   to "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    "greet_evening"     to "ಶುಭ ಸಂಜೆ",
    "greet_night"       to "ಶುಭ ರಾತ್ರಿ",
    "home_subtitle"     to "ಜಲ ಗುಣಮಟ್ಟ ಮೇಲ್ವಿಚಾರಣೆ",
    "home_wqi"          to "ಜಲ ಗುಣಮಟ್ಟ ಸೂಚ್ಯಂಕ",
    "home_region"       to "ಬೆಂಗಳೂರು ಪ್ರದೇಶ",
    "home_reports"      to "ವರದಿಗಳು",
    "home_clean"        to "ಶುದ್ಧ",
    "home_alerts"       to "ಎಚ್ಚರಿಕೆ",
    "home_actions"      to "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    "home_new_report"   to "ಹೊಸ ವರದಿ",
    "home_view_map"     to "ನಕ್ಷೆ ನೋಡಿ",
    "home_advisories"   to "ಸಲಹೆಗಳು",
    "home_recent"       to "ಇತ್ತೀಚಿನ ವರದಿಗಳು",
    "home_empty"        to "ಇನ್ನೂ ವರದಿಗಳಿಲ್ಲ",
    "home_empty_sub"    to "ನಿಮ್ಮ ಮೊದಲ ನೀರಿನ ಗುಣಮಟ್ಟ ವರದಿ ಸಲ್ಲಿಸಿ",
    "home_see_all"      to "ಎಲ್ಲಾ ನೋಡಿ",
    "home_tap_report"   to "ವಿವರಗಳಿಗೆ ಕಾರ್ಡ್ ತಟ್ಟಿ",
    "home_offline"      to "ನೀವು ಆಫ್ಲೈನ್ ಆಗಿದ್ದೀರಿ — ಸಂಗ್ರಹಿತ ಡೇಟಾ ತೋರಿಸಲಾಗುತ್ತಿದೆ",
    "home_trend"        to "7 ದಿನದ WQI ಟ್ರೆಂಡ್",
    "home_today"        to "ಇಂದು",
    "home_7d_ago"       to "7 ದಿನ ಹಿಂದೆ",
    "home_live"         to "ನೇರ",
    "home_report_brkdn" to "ವರದಿ ವಿಭಾಗ",
    "home_total_rep"    to "ಒಟ್ಟು ವರದಿಗಳು",
    "home_tap_map"      to "ಪೂರ್ಣ ನಕ್ಷೆ ತೆರೆಯಲು ತಟ್ಟಿ",
    "home_gemini_title" to "Gemini AI ಒಳನೋಟಗಳು",
    "home_gemini_insight" to "%s ದಲ್ಲಿ ನೀರಿನ ಗುಣಮಟ್ಟ ಬಹುತೇಕ ಶುದ್ಧವಾಗಿದೆ. %s ಮೂಲಗಳು ಸುರಕ್ಷಿತವಾಗಿವೆ.",
    "home_member"       to "ಸದಸ್ಯ",
    "home_days"         to "ದಿನಗಳು",
    "map_title"         to "ನೀರಿನ ನಕ್ಷೆ",
    "map_all"           to "ಎಲ್ಲಾ",
    "map_clean"         to "ಶುದ್ಧ",
    "map_moderate"      to "ಮಧ್ಯಮ",
    "map_polluted"      to "ಕಲುಷಿತ",
    "map_empty"         to "ಇಲ್ಲಿ ವರದಿಗಳಿಲ್ಲ",
    "map_empty_sub"     to "ನಕ್ಷೆಯಲ್ಲಿ ಪಿನ್ ಮಾಡಲು ವರದಿ ಸಲ್ಲಿಸಿ",
    "map_detail"        to "ನೀರಿನ ಮೂಲ ವಿವರ",
    "rep_title"         to "ವರದಿ ಸಲ್ಲಿಸಿ",
    "rep_cancel"        to "ರದ್ದು",
    "rep_photo"         to "ನೀರಿನ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    "rep_photo_hint"    to "ನೀರಿನ ಮೂಲದ ಸ್ಪಷ್ಟ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    "rep_tap_cam"       to "ಕ್ಯಾಮೆರಾ ತೆರೆಯಲು ತಟ್ಟಿ",
    "rep_retake"        to "ಮರು ತೆಗೆಯಿರಿ",
    "rep_details"       to "ನೀರಿನ ವಿವರಗಳು",
    "rep_clarity"       to "ನೀರಿನ ಸ್ಪಷ್ಟತೆ",
    "rep_murky"         to "ಕಲ್ಮಶ",
    "rep_crystal"       to "ಸ್ಫಟಿಕ ಶುದ್ಧ",
    "rep_smell"         to "ವಾಸನೆ",
    "rep_normal"        to "ಸಾಮಾನ್ಯ",
    "rep_bad"           to "ಕೆಟ್ಟ",
    "rep_flow"          to "ಹರಿವಿನ ವೇಗ",
    "rep_low"           to "ಕಡಿಮೆ",
    "rep_medium"        to "ಮಧ್ಯಮ",
    "rep_high"          to "ಹೆಚ್ಚು",
    "rep_location"      to "GPS ಸ್ಥಳ",
    "rep_loc_hint"      to "ನಕ್ಷೆಯಲ್ಲಿ ವರದಿ ಪಿನ್ ಮಾಡಲು ನಿಮ್ಮ ಸ್ಥಳ ಬೇಕು.",
    "rep_loc_cap"       to "ಸ್ಥಳ ದಾಖಲಾಯಿತು ✓",
    "rep_loc_none"      to "ಸ್ಥಳ ದಾಖಲಾಗಿಲ್ಲ",
    "rep_loc_sub"       to "GPS ನಿರ್ದೇಶಾಂಕ ಪಡೆಯಲು ಕೆಳಗೆ ತಟ್ಟಿ",
    "rep_get_loc"       to "ನನ್ನ ಸ್ಥಳ ತಿಳಿಯಿರಿ",
    "rep_refresh_loc"   to "ಸ್ಥಳ ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    "rep_continue"      to "ಮುಂದುವರಿಯಿರಿ",
    "rep_submit"        to "ವರದಿ ಸಲ್ಲಿಸಿ",
    "rep_back"          to "ಹಿಂದೆ",
    "rep_submitted"     to "ವರದಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!",
    "rep_thanks"        to "ಕೊಡುಗೆ ನೀಡಿದ್ದಕ್ಕೆ ಧನ್ಯವಾದ",
    "al_title"          to "ಎಚ್ಚರಿಕೆ ಫೀಡ್",
    "al_hint"           to "ವಜಾ ಮಾಡಲು ಎಡಕ್ಕೆ ಸ್ವೈಪ್ ಮಾಡಿ",
    "al_empty"          to "ಎಲ್ಲಾ ಸ್ಪಷ್ಟವಾಗಿದೆ!",
    "al_empty_sub"      to "ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ",
    "al_dismiss"        to "ವಜಾ",
    "al_all"            to "ಎಲ್ಲಾ",
    "adv_title"         to "AI ಸಲಹೆಗಳು",
    "adv_subtitle"      to "ಒಳನೋಟಗಳಿಗೆ ಸ್ವೈಪ್ ಮಾಡಿ",
    "adv_empty"         to "ಇನ್ನೂ ಸಲಹೆಗಳಿಲ್ಲ",
    "adv_empty_sub"     to "AI ಸಲಹೆ ಪಡೆಯಲು ವರದಿಗಳನ್ನು ಸಲ್ಲಿಸಿ",
    "pro_title"         to "ಪ್ರೊಫೈಲ್",
    "pro_reports"       to "ವರದಿಗಳು",
    "pro_streak"        to "ಸ್ಟ್ರೀಕ್",
    "pro_badges"        to "ಬ್ಯಾಡ್ಜ್‌ಗಳು",
    "pro_preferences"   to "ಆದ್ಯತೆಗಳು",
    "pro_dark"          to "ಡಾರ್ಕ್ ಮೋಡ್",
    "pro_light"         to "ಲೈಟ್ ಮೋಡ್",
    "pro_notif"         to "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
    "pro_language"      to "ಭಾಷೆ",
    "pro_about"         to "ಬಗ್ಗೆ",
    "pro_version"       to "ಅಪ್ಲಿಕೇಶನ್ ಆವೃತ್ತಿ",
    "pro_data"          to "ಡೇಟಾ ಮೂಲ",
    "pro_ai"            to "AI ಎಂಜಿನ್",
    "pro_member_for"    to "ಸದಸ್ಯ",
    "pro_days"          to "ದಿನಗಳು",
    "det_title"         to "ವರದಿ ವಿವರಗಳು",
    "det_analysis"      to "ನೀರಿನ ವಿಶ್ಲೇಷಣೆ",
    "det_ai_advisory"   to "AI ಸಲಹೆ",
    "status_clean"      to "ಶುದ್ಧ",
    "status_moderate"   to "ಮಧ್ಯಮ",
    "status_polluted"   to "ಕಲುಷಿತ",
    "close"             to "ಮುಚ್ಚಿ",
    "ai_advisory"       to "AI ಸಲಹೆ",
    "clarity"           to "ಸ್ಪಷ್ಟತೆ",
    "smell"             to "ವಾಸನೆ",
    "flow"              to "ಹರಿವು",
    "location"          to "ಸ್ಥಳ",
    "reported"          to "ವರದಿ ಮಾಡಲಾಗಿದೆ",
    "status"            to "ಸ್ಥಿತಿ",
    "share_report"      to "ನೀರಿನ ವರದಿ ಹಂಚಿ",
    "murky"             to "ಕಲ್ಮಶ",
    "crystal_clear"     to "ಸ್ಫಟಿಕ ಶುದ್ಧ",
    // AI Insights
    "ai_clean_insight"  to "✅ {region} ದಲ್ಲಿ ನೀರಿನ ಗುಣಮಟ್ಟ ಉತ್ತಮ ಸ್ಥಿತಿಯಲ್ಲಿದೆ. {total} ವರದಿಗಳಲ್ಲಿ {clean} ಶುದ್ಧ ನೀರನ್ನು ತೋರಿಸುತ್ತವೆ. ನಿಯಮಿತ ಮೇಲ್ವಿಚಾರಣೆ ಮುಂದುವರಿಸಿ.",
    "ai_mod_insight"    to "⚠️ ನೀರಿನ ಗುಣಮಟ್ಟ ಮಧ್ಯಮ ಮಟ್ಟದ ಸ್ಥಿತಿ ತೋರಿಸುತ್ತಿದೆ. ಕೆಲವು ಮೂಲಗಳಿಗೆ ಶುದ್ಧೀಕರಣ ಅಗತ್ಯ. ನೀರನ್ನು ಕುದಿಸಿ ಬಳಸಿ.",
    "ai_poll_insight"   to "🚨 {polluted} ವರದಿಗಳು ಕಲುಷಿತ ನೀರನ್ನು ಸೂಚಿಸುತ್ತವೆ. ನೇರ ಸಂಪರ್ಕ ತಪ್ಪಿಸಿ. ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳಿಗೆ ತಕ್ಷಣ ತಿಳಿಸಿ.",
    "ai_updated"        to "{total} ಸಮುದಾಯ ವರದಿಗಳ ಆಧಾರದ ಮೇಲೆ",
)
