package com.example.waterquality.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.squareup.moshi.Json
import kotlinx.serialization.Serializable

/**
 * Advisory/Alert for water quality
 * Generated by backend based on WQI score and Gemini AI analysis
 */
@Serializable
@Entity(
    tableName = "advisories",
    indices = [
        Index("timestamp"),
        Index("status")
    ]
)
data class Advisory(
    @PrimaryKey
    val id: String,

    @Json(name = "title")
    val title: String,

    @Json(name = "description")
    val description: String,

    @Json(name = "status")
    val status: String, // Critical, Caution, Safe

    @Json(name = "timestamp")
    val timestamp: Long, // Epoch milliseconds

    @Json(name = "reportId")
    val reportId: String? = null
) {
    val isCritical: Boolean
        get() = status == "Critical"

    val isCaution: Boolean
        get() = status == "Caution"

    val isSafe: Boolean
        get() = status == "Safe"

    val severityColor: String
        get() = when (status) {
            "Critical" -> "#D32F2F" // Red
            "Caution" -> "#F57C00" // Orange
            else -> "#388E3C" // Green
        }
}

